### ISSUE TITLE
RFC:  Adding a BIOL Pre-Requisite To Program

### ISSUE THREAD

**Issue by uRSTEnzY** [ossu/bioinformatics#29]
MIT recently started offering a Pre-7.01 course titled "Getting Up To Speed In Biology" (https://openlearninglibrary.mit.edu/courses/course-v1:OCW+Pre-7.01+1T2020/about).  The course was designed for students incoming to MIT who did not have the necessary background in biology from previous education.

I wanted to get some thoughts on the group before creating a PR to merge this into the baseline Bioinformatics program.

**Comment by waciumawanjohi** [comment]
I would support changing the prerequisite section from the current one:
https://github.com/ossu/bioinformatics#prerequisite
to something more like what CS has evolved to:
https://github.com/ossu/computer-science#prerequisites

And I think including a link to this course in that section would be totally appropriate.

I wouldn't support adding the course directly to the curriculum, because OSSU focuses on letting students know what constitutes the coursework for an undergraduate degree. By definition, the prerequisites for an undergraduate degree are not part of the degree itself.
